### ISSUE TITLE
inconsistent formatting

### ISSUE THREAD

**Issue by amniskin** [micha/json-table#11]
```bash
echo '[{"foo": "asdf-qwer-asdf-qwer-asdf", "bar": "poiu"},{"foo":"asdf","bar":"kjkjkj"}]' |\
  jt [ foo %=foo ] [ bar %=bar ]
```

produces the following misaligned table that's difficult to read:

```bash
foo     bar
asdf-qwer-asdf-qwer-asdf        poiu
asdf    kjkjkj
```

whereas

```bash
echo '[{"foo": "asdf-qwer-asdf-qwer-asdf", "bar": "poiu"},{"foo":"asdf","bar":"kjkjkj"}]' |\
  jt [ foo %=foo ] [ bar %=bar ] |\
  column -ts $'\t'
```

produces the desired and aligned output:

```bash
foo                       bar
asdf-qwer-asdf-qwer-asdf  poiu
asdf                      kjkjkj
```

**Comment by micha** [comment]
The output is TSV (tab separated values) by default. This is because JSON values may contain spaces, and it would be impossible to split columns if they were padded with spaces. For example:

```bash
echo '[{"foo":"one two","bar":200},{"foo":"three four","bar":400}]' \
  |jt [ foo % ] [ bar % ] \
  |awk -F\\t '$1 == "one two" {print}'
```

The `-F\\t` option to `awk` sets the input field separator to the tab character, which makes it possible to dispatch on individual columns of the output.

Since `jt` is intended to be use in shell pipelines, as plumbing, it's okay that the user chooses the display format he prefers (like the `column -ts $'\t'` in your example).

**Comment by micha** [comment]
Feel free to reopen if necessary.
